name: Generate and Deploy Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: |
            requirements.txt
            docs/requirements.txt
      - name: Install Dependencies
        run: python -m pip install --upgrade --upgrade-strategy=eager -r requirements.txt
      - name: Install Docs Dependencies
        working-directory: ./docs
        run: make installdeps
      - uses: actions/configure-pages@v5
      - name: Build pages
        working-directory: ./docs
        run: make
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html
      - uses: actions/deploy-pages@v4
